[global.limits]
forms = 32768

[development]
address = "localhost"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
template_dir = "templates/"


[staging]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
log = "normal"
template_dir = "templates/"

[production]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 5
log = "critical"
template_dir = "templates/"